### ISSUE TITLE
kinect_2d_scanner fails to build for indigo

### ISSUE THREAD

**Issue by tfoote** [mrpt-ros-pkg/kinect_2d_scanner#1]
It's failing on a missing include. This is currently the only regression in indigo released packages. 

http://build.ros.org/view/Ibin_uT64/job/Ibin_uT64__kinect_2d_scanner__ubuntu_trusty_amd64__binary/28/console

```
00:18:31 In file included from /opt/ros/indigo/include/mrpt_bridge/mrpt_bridge.h:13:0,
00:18:31                  from /tmp/binarydeb/ros-indigo-kinect-2d-scanner-0.1.1/src/kinect_2d_scanner_node.cpp:20:
00:18:31 /opt/ros/indigo/include/mrpt_bridge/utils.h:11:38: fatal error: mrpt/utils/COutputLogger.h: No such file or directory
00:18:31  #include <mrpt/utils/COutputLogger.h>
```

**Comment by tfoote** [comment]
A sync is planned for this week [this discussion](http://discourse.ros.org/t/preparing-for-indigo-sync-2016-09-21/506?u=tfoote) without more input this package will be dropped in the sync.

**Comment by jlblancoc** [comment]
Thanks @tfoote !!

Actually, I have been **exasperatingly** trying to fix this, but there must be something really stupid going on that I can't see. 

I fully understand that build error, and in theory I fixed it in the package `mrpt_bridge` after version 
0.1.14 (see [changelog](https://github.com/mrpt-ros-pkg/mrpt_navigation/blob/master/mrpt_bridge/CHANGELOG.rst)).

I think mrpt_bridge 0.1.14 has been pushed with bloom. The changelog says so. Release repo: https://github.com/mrpt-ros-pkg-release/mrpt_navigation-release

Still, while building in the build farm, the log you link says: 

> ...
> ros-indigo-mrpt-bridge: 0.1.13
> ...

What am I missing to allow mrpt_bridge to update to 0.1.16 in Indigo so the error gets fixed?

**Comment by tfoote** [comment]
0.1.13 is the version in the rosdistro: https://github.com/ros/rosdistro/blob/master/indigo/distribution.yaml#L6299

Looking at the pull requests I see one for 0.1.14 for kinetic but not indigo. https://github.com/ros/rosdistro/pulls?q=is%3Apr+mrpt_bridge+is%3Aclosed

Since you've already run bloom for 0.1.14 in indigo but just not made the pull request you can rerun bloom with the `--pull-request-only` option to recreate the needed pull request.

**Comment by jlblancoc** [comment]
Done! https://github.com/ros/rosdistro/pull/12796

Thanks, hope that was the only missing part...

**Comment by tfoote** [comment]
It has successfully built now. http://build.ros.org/view/Ibin_uT64/job/Ibin_uT64__kinect_2d_scanner__ubuntu_trusty_amd64__binary/29/

**Comment by jlblancoc** [comment]
Great!
